-- ============================================================================
-- Livraisante -- Integrite du montant paye (2026-07-22)
--
-- Contexte : create-payment-intent (Edge Function) faisait confiance au montant
-- fourni par le client (avec un garde-fou heuristique de fourchette de prix,
-- documente comme insuffisant dans son propre commentaire -- "Cela ne remplace
-- pas un calcul exact"). Un utilisateur pouvait, depuis la console du navigateur,
-- appeler sbCreatePaymentIntent(50, {}) et obtenir un vrai PaymentIntent Stripe
-- de 0,50EUR quel que soit le contenu reel du panier. Corrige ici en creant un
-- catalogue produit cote serveur (table products, ci-dessous), pour que
-- l'Edge Function puisse recalculer le montant exact a partir des articles
-- (laboratoire + nom) envoyes par le client, sans jamais faire confiance a un
-- montant total fourni directement par le navigateur.
--
-- Donnees : copie exacte du catalogue client PRODUCT_CATALOG (index.html),
-- dedupliquee par (lab, name) -- aucun conflit de prix trouve entre categories
-- pour les memes couples (lab, name) sur les 322 references du catalogue.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lab text NOT NULL,
  name text NOT NULL,
  dosage text,
  prix numeric(10,2) NOT NULL CHECK (prix > 0),
  category text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lab, name)
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_public_read" ON public.products;
CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "products_admin_write" ON public.products;
CREATE POLICY "products_admin_write"
  ON public.products FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Seed depuis le catalogue client (source de verite jusqu'ici, desormais dupliquee
-- cote serveur pour que le prix ne soit plus jamais uniquement declaratif client).
INSERT INTO public.products (lab, name, dosage, prix, category) VALUES
  ('Nutergia', 'Ergymag', '300 mg bisglycinate · 90 gél.', 22.9, 'Magnésium'),
  ('Pileje', 'Magnesium Pileje 300mg', '60 comprimés', 15.5, 'Magnésium'),
  ('Forté Pharma', 'Turbo Magnésium 300+', '30 comprimés effervescents', 11.5, 'Magnésium'),
  ('Arkopharma', 'Magnésium Marin Arkopharma', '60 gélules', 10.5, 'Magnésium'),
  ('Solgar', 'Magnésium Chélaté Solgar', '100 mg · 100 comprimés', 17.5, 'Magnésium'),
  ('NHCO', 'Mg++ NHCO', '84 gélules', 21.35, 'Magnésium'),
  ('Aragan', 'Magnésium Marin Aragan', '60 gélules', 12.5, 'Magnésium'),
  ('Bayer', 'Berocca Magnésium', '60 comprimés effervescents', 9.9, 'Magnésium'),
  ('Bayer', 'Supradyn Magnesia', '30 comprimés effervescents', 10.9, 'Magnésium'),
  ('Arkopharma', 'Vitamine B2 Arkopharma 400mg', '60 gélules', 11.9, 'Vitamine B2 (riboflavine)'),
  ('Solgar', 'Riboflavine Solgar', '100mg · 100 gél.', 13.9, 'Vitamine B2 (riboflavine)'),
  ('Forté Pharma', 'Forté Vit B2', '30 comprimés', 9.9, 'Vitamine B2 (riboflavine)'),
  ('BSN Radiante', 'Compresse Froide Instantanée BSN Radiante', 'usage unique', 7.5, 'Compresse froide / chaud-froid'),
  ('Cooper', 'Compresse Froide/Chaude Cooper', 'réutilisable', 8.9, 'Compresse froide / chaud-froid'),
  ('Lea Nature', 'Tisane Camomille Bio Jardin Bio', '20 sachets', 4.2, 'Tisane relaxante (camomille / mélisse)'),
  ('Les 3 Chênes', 'Tisane Mélisse-Camomille Les 3 Chênes', '20 sachets', 5.2, 'Tisane relaxante (camomille / mélisse)'),
  ('Arkopharma', 'Arkofluides Camomille Mélisse', '20 ampoules', 8.9, 'Tisane relaxante (camomille / mélisse)'),
  ('Weleda', 'Tisane Relaxante Weleda', '20 sachets', 6.5, 'Tisane relaxante (camomille / mélisse)'),
  ('Gifrer', 'Sérums Physiologiques Gifrer Adultes', 'unidoses 5mL × 40', 4.45, 'Spray nasal isotonique (eau de mer)'),
  ('Cooper', 'Spray Nasal Isotonique Cooper', '100 mL', 6.25, 'Spray nasal isotonique (eau de mer)'),
  ('Marimer', 'Marimer Isotonique Hygiène Nasale', '100 mL', 5.11, 'Spray nasal isotonique (eau de mer)'),
  ('Forté Pharma', 'Turbo Vit C 1000mg + Zinc', '30 comprimés effervescents', 9.9, 'Vitamine C + Zinc'),
  ('Pileje', 'Vitamine C + Zinc Pileje', '60 comprimés', 11.9, 'Vitamine C + Zinc'),
  ('Arkopharma', 'Vitamine C 1000mg + Zinc Arkopharma', 'effervescent × 20', 9.5, 'Vitamine C + Zinc'),
  ('Solgar', 'Solgar Vitamin C 1000mg + Zinc', '100 gélules', 14.9, 'Vitamine C + Zinc'),
  ('NHCO', 'C+Zinc NHCO', 'ampoules', 16.9, 'Vitamine C + Zinc'),
  ('Aragan', 'C + Zinc Aragan', '30 sachets', 10.9, 'Vitamine C + Zinc'),
  ('Bayer', 'Berocca Energie', '15 comprimés effervescents', 5.99, 'Vitamine C + Zinc'),
  ('Bayer', 'Berocca Immunité Flash', '20 comprimés effervescents', 7.49, 'Vitamine C + Zinc'),
  ('UPSA', 'Vitamine C 1000mg Effervescent UPSA', '20 comprimés effervescents', 4.5, 'Vitamine C + Zinc'),
  ('Arkopharma', 'Arkogélules Échinacée', '45 gélules', 13.5, 'Échinacée (extrait standardisé)'),
  ('Santé Verte', 'Échinacée Santé Verte', '20 ampoules', 11.9, 'Échinacée (extrait standardisé)'),
  ('Les 3 Chênes', 'Échinacée Les 3 Chênes', '60 gélules', 12.9, 'Échinacée (extrait standardisé)'),
  ('PureEssentiel', 'Défenses Immunitaires PureEssentiel', '30 gélules', 13.9, 'Échinacée (extrait standardisé)'),
  ('Les 3 Chênes', 'Propolis Forte Les 3 Chênes', '60 gélules', 12.9, 'Propolis'),
  ('Santé Verte', 'Propolis Verte Santé Verte', '45 gélules', 11.9, 'Propolis'),
  ('PureEssentiel', 'Propolis PureEssentiel', 'spray + gélules', 13.5, 'Propolis'),
  ('Lea Nature', 'Propolis Bio Lea Nature', '20 sachets miel-propolis', 8.9, 'Propolis'),
  ('Les 3 Chênes', 'Propolis Spray Buccal Les 3 Chênes', '25 mL', 9.9, 'Propolis spray (voie locale)'),
  ('Santé Verte', 'Propolis Spray Gorge Santé Verte', '30 mL', 9.5, 'Propolis spray (voie locale)'),
  ('PureEssentiel', 'Spray Gorge PureEssentiel', '15 mL', 10.9, 'Propolis spray (voie locale)'),
  ('PureEssentiel', 'Spray Gorge Adoucissant PureEssentiel', '15 mL — DM', 9.5, 'Spray adoucissant gorge'),
  ('Cooper', 'Spray Gorge Adoucissant Cooper', '20 mL — DM', 8.9, 'Spray adoucissant gorge'),
  ('Les 3 Chênes', 'Pastilles Miel Propolis Zinc Les 3 Chênes', '36 pastilles', 8.9, 'Zinc + miel (pastilles adoucissantes)'),
  ('Lea Nature', 'Pastilles Miel Citron Zinc Bio', '20 pastilles', 7.5, 'Zinc + miel (pastilles adoucissantes)'),
  ('Forté Pharma', 'Zinc Miel Gorge Forté Pharma', '24 pastilles', 8.9, 'Zinc + miel (pastilles adoucissantes)'),
  ('Pranarom', 'HE Eucalyptus Radiata Pranarom', '10 mL bio', 7.2, 'Huile essentielle eucalyptus / thym'),
  ('PureEssentiel', 'HE Thym à Thymol PureEssentiel', '10 mL', 8.9, 'Huile essentielle eucalyptus / thym'),
  ('Arkopharma', 'HE Eucalyptus Arkopharma', '10 mL', 7.5, 'Huile essentielle eucalyptus / thym'),
  ('Pileje', 'Lactibiane Référence', '30 gélules — 10 Md UFC', 28.15, 'Probiotiques digestifs'),
  ('Nutergia', 'Ergyflor', '20 sachets', 19.5, 'Probiotiques digestifs'),
  ('Solgar', 'Probiotiques Advanced 50 Milliards Solgar', '30 gélules', 25.9, 'Probiotiques digestifs'),
  ('NHCO', 'Probiotiques NHCO', '30 gélules', 22.5, 'Probiotiques digestifs'),
  ('Opella', 'Microbiosys Confort Digestif', '30 gélules — 3 souches Lactobacillus', 11, 'Probiotiques digestifs'),
  ('Opella', 'Microbiosys Ballonnements', '30 gélules — Lactobacillus + FOS', 10, 'Probiotiques digestifs'),
  ('Procter & Gamble', 'Bion3 Défense Adulte', '30 comprimés — probiotiques + multivitamines', 11.49, 'Probiotiques digestifs'),
  ('Arkopharma', 'Arkogélules Gingembre', '45 gélules', 11.9, 'Gingembre (extrait standardisé)'),
  ('Santé Verte', 'Gingembre Santé Verte', '60 gélules', 10.9, 'Gingembre (extrait standardisé)'),
  ('Les 3 Chênes', 'Gingembre Les 3 Chênes', '30 gélules', 9.9, 'Gingembre (extrait standardisé)'),
  ('Pileje', 'Digest+ Pileje', '30 gélules', 14.5, 'Enzymes digestives'),
  ('NHCO', 'Digestif Enzymes NHCO', '60 gélules', 16.9, 'Enzymes digestives'),
  ('Nutergia', 'Ergydigest', '60 gélules', 14.9, 'Enzymes digestives'),
  ('Arkopharma', 'Arkogélules Charbon Végétal', '45 gélules', 8.9, 'Charbon végétal actif'),
  ('Forté Pharma', 'Charbon Végétal Activé Forté Pharma', '60 gélules', 7.55, 'Charbon végétal actif'),
  ('Les 3 Chênes', 'Charbon Végétal Les 3 Chênes', '60 gélules', 9.5, 'Charbon végétal actif'),
  ('Reckitt', 'Dioralyte Saveur Citron', 'sachets × 6 — DM CE', 9.9, 'Solution de réhydratation orale (SRO)'),
  ('Cooper', 'SRO Cooper', 'sachets × 10 — DM CE', 8.9, 'Solution de réhydratation orale (SRO)'),
  ('Solgar', 'Zinc Picolinate Solgar 22mg', '100 comprimés', 10.75, 'Zinc'),
  ('Nutergia', 'Ergyzinc', '60 gélules', 11.5, 'Zinc'),
  ('NHCO', 'Zinc+ NHCO', '30 comprimés', 14.5, 'Zinc'),
  ('Forté Pharma', 'Zinc 15mg Expert Forté Pharma', '60 comprimés', 8.5, 'Zinc'),
  ('Kenvue', 'Band-Aid Assortiment Kenvue', '40 pansements — DM', 7.9, 'Pansements / compresses stériles'),
  ('BSN Radiante', 'Elastoplast Compresses Stériles BSN', 'boîte 20 × 5cm — DM', 6.9, 'Pansements / compresses stériles'),
  ('Cooper', 'Compresses Stériles Cooper', '10 × 10cm · 50 sachets — DM', 7.5, 'Pansements / compresses stériles'),
  ('Gifrer', 'Sérum Physiologique Gifrer', 'unidoses 5mL × 40 — DM', 6.5, 'Solution saline (lavage de plaie)'),
  ('Cooper', 'Solution Saline Isotonique Cooper', 'spray 100mL — DM', 6.9, 'Solution saline (lavage de plaie)'),
  ('Klorane', 'Gel Apaisant Aloe Vera Klorane', '50 mL', 9.5, 'Gel aloe vera'),
  ('Lea Nature', 'Gel Aloe Vera Bio Lea Nature', '100 mL', 8.9, 'Gel aloe vera'),
  ('Laboratoire de Biarritz', 'Aloe Vera Bio Pur Lab de Biarritz', '100 mL', 10.9, 'Gel aloe vera'),
  ('Pranarom', 'HE Lavande Vraie Pranarom', '10 mL bio', 9.9, 'Huile essentielle lavande vraie'),
  ('PureEssentiel', 'HE Lavande Officinale PureEssentiel', '10 mL', 9.5, 'Huile essentielle lavande vraie'),
  ('Cooper', 'Aspivenin Extracteur de Venin Cooper', 'kit — DM', 9.9, 'Extracteur de venin'),
  ('Kenvue', 'Kit Extracteur Piqûres Kenvue', 'DM', 10.9, 'Extracteur de venin'),
  ('PureEssentiel', 'Roll-On Après Piqûre PureEssentiel', '5 mL', 9.9, 'Roll-on apaisant post-piqûre (HE)'),
  ('Pranarom', 'Roll-On Apaisant Pranarom', '10 mL', 9.5, 'Roll-on apaisant post-piqûre (HE)'),
  ('Pileje', 'Curcumaxx C3 Complex Pileje', '60 gélules', 14.9, 'Curcumine'),
  ('NHCO', 'Curcumine+ NHCO', '30 gélules', 17.9, 'Curcumine'),
  ('Arkopharma', 'Curcuma 500mg Arkopharma', '45 gélules', 13.5, 'Curcumine'),
  ('Solgar', 'Curcumine Full Spectrum Solgar', '60 gélules', 22.9, 'Curcumine'),
  ('Pileje', 'Oméganut Pileje', '60 gélules · EPA 450mg/DHA 300mg', 17.5, 'Oméga‑3 (EPA/DHA)'),
  ('Nutergia', 'Ergyomega', '60 gélules', 16.9, 'Oméga‑3 (EPA/DHA)'),
  ('Solgar', 'Oméga-3 950mg Solgar', '100 gélules', 22.9, 'Oméga‑3 (EPA/DHA)'),
  ('NHCO', 'EPA/DHA NHCO', '60 gélules', 21.5, 'Oméga‑3 (EPA/DHA)'),
  ('Arkopharma', 'Arkog Oméga-3 Marin', '180 capsules', 21.15, 'Oméga‑3 (EPA/DHA)'),
  ('Procter & Gamble', 'Bion3 Oméga 3', '60 gélules — EPA 300mg / DHA 200mg', 18.89, 'Oméga‑3 (EPA/DHA)'),
  ('BSN Radiante', 'Patch Chauffant BSN Radiante', '3 patches — DM', 9.9, 'Patch thermique'),
  ('Cooper', 'Patch Thermique Cooper', '3 patches — DM', 8.9, 'Patch thermique'),
  ('Donjoy', 'Chevillère Reaction Donjoy', 'taille S/M/L — DM', 29.9, 'Orthèse / soutien articulaire'),
  ('Donjoy', 'Genouillère Donjoy Tightner', 'taille universelle — DM', 34.9, 'Orthèse / soutien articulaire'),
  ('Orliman', 'Chevillière Élastique Orliman', 'taille au choix — DM', 24.9, 'Orthèse / soutien articulaire'),
  ('Orliman', 'Genouillère Rotulienne Orliman', 'DM', 28.9, 'Orthèse / soutien articulaire'),
  ('Forté Pharma', 'Turbo Mélatonine 1.9mg Forté Pharma', '30 comprimés', 8.55, 'Mélatonine (faible dose — CA)'),
  ('Pileje', 'Mélatonine 1mg Pileje', '60 comprimés', 12.25, 'Mélatonine (faible dose — CA)'),
  ('NHCO', 'Mélatonine 1mg NHCO', '30 comprimés', 14.9, 'Mélatonine (faible dose — CA)'),
  ('Nutergia', 'Mélatoni+ Nutergia', '30 gélules', 12.9, 'Mélatonine (faible dose — CA)'),
  ('Arkopharma', 'Mélatonine 1mg Arkopharma', '30 comprimés', 9.5, 'Mélatonine (faible dose — CA)'),
  ('Opella', 'Novanuit Triple Action', '40 comprimés — mélatonine 1mg + valériane + passiflore', 11.9, 'Mélatonine (faible dose — CA)'),
  ('Opella', 'Novanuit Nuit Complète', '30 comprimés — mélatonine 1,9mg', 12.55, 'Mélatonine (faible dose — CA)'),
  ('Procter & Gamble', 'ZzzQuil Sommeil Gummies', '48 gummies — mélatonine 1mg', 10.69, 'Mélatonine (faible dose — CA)'),
  ('Procter & Gamble', 'ZzzQuil Nuit Complète', '30 comprimés — mélatonine 1,9mg + passiflore', 11.98, 'Mélatonine (faible dose — CA)'),
  ('UPSA', 'Gummies 7en1 Sommeil UPSA', '40 gummies — mélatonine 1mg + valériane', 18.29, 'Mélatonine (faible dose — CA)'),
  ('Arkopharma', 'Arkorelax Sommeil Valériane Mélisse', '30 comprimés', 9.9, 'Valériane + Mélisse'),
  ('Les 3 Chênes', 'Valériane Mélisse Les 3 Chênes', '60 gélules', 9.9, 'Valériane + Mélisse'),
  ('Santé Verte', 'Valériane Complex Santé Verte', '30 gélules', 10.9, 'Valériane + Mélisse'),
  ('Weleda', 'Mélisse-Valériane Weleda', '20 ampoules', 12.9, 'Valériane + Mélisse'),
  ('Arkopharma', 'Arkogélules Passiflore', '45 gélules', 9.9, 'Passiflore (extrait)'),
  ('Santé Verte', 'Passiflore Santé Verte', '60 gélules', 10.5, 'Passiflore (extrait)'),
  ('Weleda', 'Passiflore Weleda', '20 ampoules', 11.9, 'Passiflore (extrait)'),
  ('Solgar', 'Quercétine Complexe Solgar', '100 gélules', 14.9, 'Quercétine'),
  ('NHCO', 'Quercétine NHCO', '30 gélules', 16.9, 'Quercétine'),
  ('Nutergia', 'Ergyquercétine', '60 gélules', 14.9, 'Quercétine'),
  ('Arkopharma', 'Arkogélules Spiruline', '45 gélules', 12.9, 'Spiruline'),
  ('Les 3 Chênes', 'Spiruline Les 3 Chênes', '60 comprimés', 11.9, 'Spiruline'),
  ('Aragan', 'Spiruline Premium Aragan', '60 gélules', 12.5, 'Spiruline'),
  ('Nutergia', 'Ergyvital Spiruline', '90 comprimés', 13.9, 'Spiruline'),
  ('Nutergia', 'Ergyprotein Nutergia', 'sachet 500g', 24.9, 'Protéines (whey / caséine)'),
  ('NHCO', 'Whey Protéines NHCO', '700g', 28.9, 'Protéines (whey / caséine)'),
  ('Aragan', 'Whey Protéines Aragan', '500g', 23.9, 'Protéines (whey / caséine)'),
  ('Solgar', 'Créatine Monohydrate Solgar', '60 gélules 1g', 17.9, 'Créatine monohydrate'),
  ('Nutergia', 'Ergycreatine', '100g poudre', 18.9, 'Créatine monohydrate'),
  ('Forté Pharma', 'Forté Créatine Sport', '90 gélules', 16.9, 'Créatine monohydrate'),
  ('Pileje', 'D-Biane Pileje 1000UI', '60 comprimés', 7.5, 'Vitamine D'),
  ('Nutergia', 'Ergyvit D3', '60 gélules · 2000UI', 8.55, 'Vitamine D'),
  ('Forté Pharma', 'Fortévit D3 Expert', '30 gélules · 2000UI', 7.9, 'Vitamine D'),
  ('Arkopharma', 'Vitamine D3 Arkopharma 1000UI', '90 gélules', 7.2, 'Vitamine D'),
  ('Solgar', 'Vitamine D3 1000UI Solgar', '100 gélules', 8.55, 'Vitamine D'),
  ('Pileje', 'D3K2+Calcium Pileje', '60 gélules', 13.5, 'Calcium (+ vitamine D)'),
  ('Nutergia', 'Ergycalcium', '90 comprimés', 14.5, 'Calcium (+ vitamine D)'),
  ('Solgar', 'Calcium 600mg + D3 Solgar', '120 comprimés', 15.9, 'Calcium (+ vitamine D)'),
  ('Pileje', 'Fe+ Pileje', '30 gélules', 10.5, 'Fer'),
  ('NHCO', 'Fer Plus NHCO', '30 gélules', 14.5, 'Fer'),
  ('Nutergia', 'Ergyfer', '20 ampoules', 12.9, 'Fer'),
  ('Aragan', 'Fer + Vit C Aragan', '60 comprimés', 11.5, 'Fer'),
  ('Procter & Gamble', 'Femibion 2 — 2e-3e trimestre', '28+28 comp. — DHA + fer + méthylfolate', 23.49, 'Fer'),
  ('Pileje', 'Collagène Marin + Vit C Pileje', '30 sachets', 26.5, 'Collagène + vitamine C'),
  ('NHCO', 'Marine Collagen NHCO', '30 gélules', 29.9, 'Collagène + vitamine C'),
  ('Forté Pharma', 'Collagène Marin 10 000mg Forté Pharma', '20 sachets', 21.15, 'Collagène + vitamine C'),
  ('Dielen', 'Collagène Caps Dielen', '60 capsules', 24.4, 'Collagène + vitamine C'),
  ('UPSA', 'Gummies 7en1 Collagène UPSA', '50 gummies — collagène marin + vit C', 23.79, 'Collagène + vitamine C'),
  ('Arkopharma', 'Jus Cerise Montmorency Arkopharma', '500mL concentré', 17.9, 'Jus de cerise de Montmorency'),
  ('Les 3 Chênes', 'Cerise Montmorency Les 3 Chênes', '60 gélules', 16.9, 'Jus de cerise de Montmorency'),
  ('Santé Verte', 'Cerise Montmorency Santé Verte', '60 gélules', 17.5, 'Jus de cerise de Montmorency'),
  ('Nutergia', 'Ergyelectro Sport', '30 sachets', 11.9, 'Électrolytes (sodium, potassium)'),
  ('NHCO', 'Électrolytes Sport NHCO', '20 sachets', 13.9, 'Électrolytes (sodium, potassium)'),
  ('Forté Pharma', 'Électrolytes Sport Forté Pharma', '30 sachets effervescents', 10.9, 'Électrolytes (sodium, potassium)'),
  ('Pileje', 'Articulatio Glucosamine Pileje', '60 gélules', 19.5, 'Glucosamine / chondroïtine'),
  ('NHCO', 'Articulaire Glucosamine NHCO', '30 gélules', 24.4, 'Glucosamine / chondroïtine'),
  ('Solgar', 'Glucosamine 1000mg Solgar', '60 comprimés', 23.9, 'Glucosamine / chondroïtine'),
  ('Boiron', 'Arnigel 7%', 'Gel 45g — application locale', 7.9, 'Arnica gel (application locale)'),
  ('Lehning', 'Arnica Montana Gel', 'Gel 50g — massage', 6.9, 'Arnica gel (application locale)'),
  ('Weleda', 'Arnica Gel Corps', 'Gel 100ml — soin musculaire', 9.5, 'Arnica gel (application locale)'),
  ('Pranarom', 'HE Gaulthérie couchée BIO', '10 ml — usage topique dilué', 8.9, 'Huile essentielle de gaulthérie (wintergreen)'),
  ('Florame', 'HE Gaulthérie BIO', '10 ml', 9.5, 'Huile essentielle de gaulthérie (wintergreen)'),
  ('Puressentiel', 'HE Wintergreen', '10 ml — muscles et articulations', 8.5, 'Huile essentielle de gaulthérie (wintergreen)'),
  ('Thuasne', 'Lomba Fix ceinture de soutien', 'Taille S à XXL', 34.9, 'Orthèse lombaire'),
  ('Gibaud', 'Ceinture lombaire Stelom', 'Taille ajustable', 29.9, 'Orthèse lombaire'),
  ('Bioderma', 'Atoderm Intensive Baume', '200ml — peau atopique', 14.9, 'Émollient / crème hydratante peaux sensibles'),
  ('La Roche-Posay', 'Lipikar Baume AP+', '200ml — peaux sèches à atopiques', 16.9, 'Émollient / crème hydratante peaux sensibles'),
  ('Avène', 'XeraCalm A.D Baume', '200ml — peau atopique', 15.5, 'Émollient / crème hydratante peaux sensibles'),
  ('Uriage', 'Xémose Crème Universelle', '150ml — peaux sèches', 13.9, 'Émollient / crème hydratante peaux sensibles'),
  ('Phytema', 'Huile de Bourrache Bio', '60 capsules — 500mg/caps', 12.9, 'Huile végétale de bourrache'),
  ('Nutergia', 'Ergyflex Bourrache Onagre', '60 capsules', 14.9, 'Huile végétale de bourrache'),
  ('Arkopharma', 'Arkogélules Bourrache', '45 capsules', 11.9, 'Huile végétale de bourrache'),
  ('La Roche-Posay', 'Effaclar Sérum 10% Niacinamide', '30ml — acné et pores', 19.9, 'Niacinamide (application locale)'),
  ('Avène', 'Cleanance Concentrate Sérum', '30ml — peaux à tendance acnéique', 17.9, 'Niacinamide (application locale)'),
  ('Bioderma', 'Sébium Serum Niacinamide', '40ml — sébum et brillances', 18.5, 'Niacinamide (application locale)'),
  ('Pileje', 'Floragynes Canneberge', '30 gélules — 36mg PAC/gél.', 13.9, 'Canneberge (cranberry, extrait normalisé PAC)'),
  ('Arkopharma', 'Arkogélules Canneberge BIO', '45 gélules', 11.9, 'Canneberge (cranberry, extrait normalisé PAC)'),
  ('Nutergia', 'Ergycanneberge', '30 gélules — extrait normalisé', 14.5, 'Canneberge (cranberry, extrait normalisé PAC)'),
  ('Forté Pharma', 'Cys-Control Canneberge', '30 gélules', 12.9, 'Canneberge (cranberry, extrait normalisé PAC)'),
  ('Nutergia', 'D-Mannose Nutergia', '60 gélules — 500mg/gél.', 16.9, 'D-mannose'),
  ('Pileje', 'D-Mannose Pileje', '30 gélules', 15.9, 'D-mannose'),
  ('Solgar', 'D-Mannose with Cranberry', '60 gélules', 18.9, 'D-mannose'),
  ('Pileje', 'Floragynes Probiotiques', '30 gélules — Lactobacillus rhamnosus', 20.42, 'Probiotiques gynécologiques'),
  ('Nutergia', 'Ergyphilus Intima', '60 gélules — Lactobacillus', 20.42, 'Probiotiques gynécologiques'),
  ('Arkopharma', 'Arkoflor Féminin', '28 gélules', 18.5, 'Probiotiques gynécologiques'),
  ('Procter & Gamble', 'Femibion Intime', '28 gélules — Lactobacillus rhamnosus + reuteri', 18.99, 'Probiotiques gynécologiques'),
  ('Altheapharma', 'Bicarbonate de soude alimentaire', '250g — qualité alimentaire', 3.9, 'Bicarbonate de sodium alimentaire'),
  ('La Vie Claire', 'Bicarbonate Alimentaire', '500g', 4.5, 'Bicarbonate de sodium alimentaire'),
  ('Arkopharma', 'Arkogélules Fenouil', '45 gélules — spasmes digestifs', 9.9, 'Méprobamate intestinal (antispasmodique doux)'),
  ('Pileje', 'Confort Intestinal Pileje', '30 gélules', 13.9, 'Méprobamate intestinal (antispasmodique doux)'),
  ('Pranarom', 'HE Menthe Poivrée BIO Pranarom', '10 mL', 7.9, 'Huile essentielle de menthe poivrée (vv)'),
  ('PureEssentiel', 'HE Menthe Poivrée PureEssentiel', '10 mL', 8.5, 'Huile essentielle de menthe poivrée (vv)'),
  ('Arkopharma', 'Arkogélules Carvi', '45 gélules', 9.9, 'Cumin / Carvi (extrait)'),
  ('Les 3 Chênes', 'Cumin-Carvi Les 3 Chênes', '60 gélules', 10.5, 'Cumin / Carvi (extrait)'),
  ('Cooper', 'Carbonate de Calcium Cooper', '60 comprimés à croquer', 6.9, 'Carbonate de calcium (antiacide naturel)'),
  ('Gilbert', 'Calcium Carbonate Gilbert', '30 sachets', 7.5, 'Carbonate de calcium (antiacide naturel)'),
  ('Lea Nature', 'Jus Aloe Vera Bio Lea Nature', '500 mL', 12.9, 'Aloe vera (jus/extrait — usage digestif)'),
  ('Arkopharma', 'Arko Aloe Vera', '30 gélules', 10.5, 'Aloe vera (jus/extrait — usage digestif)'),
  ('Solgar', 'DGL Réglisse Solgar', '100 comprimés à croquer', 14.9, 'Réglisse DGL (déglycyrrhizinée)'),
  ('Arkopharma', 'Arkogélules Réglisse', '45 gélules', 9.9, 'Réglisse DGL (déglycyrrhizinée)'),
  ('Arkopharma', 'Arkogélules Gingembre Fort', '30 gélules', 12.9, 'Gingembre + Mélatonine (anti-nausée)'),
  ('Santé Verte', 'Nausées Gingembre Santé Verte', '30 comprimés', 10.9, 'Gingembre + Mélatonine (anti-nausée)'),
  ('Arkopharma', 'Vitamine B6 Arkopharma', '60 gélules 10mg', 8.9, 'Vitamine B6 (anti-nausée)'),
  ('Pileje', 'Vitamine B6 Pileje', '60 comprimés', 9.9, 'Vitamine B6 (anti-nausée)'),
  ('Solgar', 'Vitamine B6 50mg Solgar', '100 comprimés', 11.9, 'Vitamine B6 (anti-nausée)'),
  ('Solgar', 'Vitamine C 500mg Solgar', '100 comprimés', 14.95, 'Vitamine C 500mg'),
  ('Arkopharma', 'Vitamine C 500mg Arkopharma', '60 gélules', 9.9, 'Vitamine C 500mg'),
  ('Pileje', 'Vitamine C Pileje 500mg', '60 comprimés', 12.9, 'Vitamine C 500mg'),
  ('Granions', 'Vitamine C Liposomale Granions', '60 comprimés', 17.45, 'Vitamine C 500mg'),
  ('UPSA', 'Acérola 1000 Bio UPSA', '24 comprimés à croquer', 7.99, 'Vitamine C 500mg'),
  ('Ixora', 'Vitamine D3 1000 UI Ixora', '60 gélules', 7.25, 'Vitamine D3 1000 UI'),
  ('Pileje', 'D-Biane 1000UI Pileje', '60 comprimés', 7.5, 'Vitamine D3 1000 UI'),
  ('Solgar', 'Zinc 15mg Picolinate Solgar', '100 comprimés', 10.75, 'Zinc 15mg'),
  ('Pileje', 'Zinc 15mg Pileje', '60 comprimés', 11.5, 'Zinc 15mg'),
  ('Ixora', 'Zinc 15mg Ixora', '60 gélules', 9.5, 'Zinc 15mg'),
  ('Ballot-Flurin', 'Propolis Rouge Ballot-Flurin', '40 gélules — extrait sec', 19.9, 'Propolis extrait'),
  ('Pileje', 'Échinacée Pileje', '30 gélules', 12.9, 'Echinacea (Arkopharma)'),
  ('Arkopharma', 'Arkogélules Thé Vert', '45 gélules', 10.9, 'Thé vert extrait'),
  ('Santé Verte', 'Thé Vert Santé Verte', '60 gélules', 10.5, 'Thé vert extrait'),
  ('Les 3 Chênes', 'Thé Vert Les 3 Chênes', '60 gélules', 11.5, 'Thé vert extrait'),
  ('Nutreov', 'Konjac 700mg Nutreov', '60 gélules', 14.9, 'Konjac gélules'),
  ('Arkopharma', 'Arkogélules Konjac', '45 gélules', 12.9, 'Konjac gélules'),
  ('Les 3 Chênes', 'Konjac Les 3 Chênes', '60 gélules', 12.5, 'Konjac gélules'),
  ('Solgar', 'Chrome Polynicotinate Solgar 200µg', '90 gélules', 11.9, 'Chrome 200µg'),
  ('Arkopharma', 'Chrome 200µg Arkopharma', '60 gélules', 9.9, 'Chrome 200µg'),
  ('Ixora', 'Chrome 200µg Ixora', '60 gélules', 9.5, 'Chrome 200µg'),
  ('Pileje', 'Hepatobiane Pileje', '60 gélules — artichaut+radis noir', 14.9, 'Artichaut + Radis noir'),
  ('Arkopharma', 'Arkogélules Artichaut', '45 gélules', 10.9, 'Artichaut + Radis noir'),
  ('Nutergia', 'Ergydetox Artichaut', '60 gélules', 14.5, 'Artichaut + Radis noir'),
  ('Nutreov', 'CLA 1000mg Nutreov', '60 gélules', 16.9, 'CLA 1000mg'),
  ('Solgar', 'CLA 1000mg Solgar', '60 gélules', 17.9, 'CLA 1000mg'),
  ('Forté Pharma', 'CLA Sport Forté Pharma', '60 gélules', 15.9, 'CLA 1000mg'),
  ('Pileje', 'Bêta-carotène 6mg Pileje', '60 gélules', 11.9, 'Bêta-carotène 6mg'),
  ('Solgar', 'Natural Beta Carotene Solgar 6mg', '180 gélules', 14.9, 'Bêta-carotène 6mg'),
  ('Arkopharma', 'Bêta-Carotène Arkopharma', '45 gélules', 10.9, 'Bêta-carotène 6mg'),
  ('Solgar', 'Lycopène 10mg Solgar', '60 gélules', 14.9, 'Lycopène 10mg'),
  ('NHCO', 'Lycopène 10mg NHCO', '30 gélules', 16.9, 'Lycopène 10mg'),
  ('Nutergia', 'Ergylyco 10mg', '60 gélules', 14.5, 'Lycopène 10mg'),
  ('Solgar', 'Astaxanthine 4mg Solgar', '30 gélules', 19.9, 'Astaxanthine 4mg'),
  ('NHCO', 'Astaxanthine 4mg NHCO', '30 gélules', 18.9, 'Astaxanthine 4mg'),
  ('Nutergia', 'Ergyastax 4mg', '30 gélules', 17.9, 'Astaxanthine 4mg'),
  ('Ixora', 'Sélénium 200µg Ixora', '60 gélules', 9.5, 'Sélénium 200µg'),
  ('Solgar', 'Sélénium 200µg Solgar', '100 comprimés', 10.9, 'Sélénium 200µg'),
  ('Arkopharma', 'Sélénium 200µg Arkopharma', '60 gélules', 9.9, 'Sélénium 200µg'),
  ('Solgar', 'Vitamine E 400UI Solgar', '50 gélules', 16.9, 'Vitamine E 400 UI'),
  ('Arkopharma', 'Vitamine E 400UI Arkopharma', '30 gélules', 13.9, 'Vitamine E 400 UI'),
  ('NHCO', 'Vitamine E Naturelle NHCO', '30 gélules', 15.9, 'Vitamine E 400 UI'),
  ('Solgar', 'Lutéine 20mg Solgar', '60 gélules', 18.9, 'Lutéine 20mg'),
  ('NHCO', 'Lutéine 20mg NHCO', '30 gélules', 17.9, 'Lutéine 20mg'),
  ('Arkopharma', 'Lutéine 20mg Arkopharma', '30 gélules', 15.9, 'Lutéine 20mg'),
  ('Pileje', 'Oméganut DHA 500mg Pileje', '60 gélules', 17.5, 'Oméga-3 DHA 500mg'),
  ('Nutergia', 'Ergyomega DHA', '60 gélules', 16.9, 'Oméga-3 DHA 500mg'),
  ('Solgar', 'Oméga-3 DHA 500mg Solgar', '100 gélules', 22.9, 'Oméga-3 DHA 500mg'),
  ('Procter & Gamble', 'Femibion 1 — 1er trimestre', '28 comprimés — DHA + méthylfolate', 19.98, 'Oméga-3 DHA 500mg'),
  ('Solgar', 'Zinc + Cuivre Solgar', '100 comprimés', 10.9, 'Zinc + Cuivre'),
  ('Pileje', 'Zinc + Cuivre Pileje', '60 gélules', 11.9, 'Zinc + Cuivre'),
  ('NHCO', 'Zinc-Cuivre NHCO', '30 gélules', 13.9, 'Zinc + Cuivre'),
  ('Ixora', 'Riboflavine B2 Ixora', '60 gélules', 9.5, 'Riboflavine B2'),
  ('Arkopharma', 'Vitamine B2 400mg Arkopharma', '60 gélules', 11.9, 'Riboflavine B2'),
  ('Solgar', 'Riboflavine Solgar 100mg', '100 gélules', 13.9, 'Riboflavine B2'),
  ('Arkopharma', 'Arkogélules Myrtille', '45 gélules', 12.9, 'Myrtille extrait'),
  ('Santé Verte', 'Myrtille Santé Verte', '60 gélules', 11.9, 'Myrtille extrait'),
  ('Les 3 Chênes', 'Myrtille Les 3 Chênes', '60 gélules', 12.5, 'Myrtille extrait'),
  ('Arkopharma', 'Arkogélules Vigne Rouge', '45 gélules', 11.9, 'Vigne rouge extrait'),
  ('Santé Verte', 'Vigne Rouge Santé Verte', '60 gélules', 10.9, 'Vigne rouge extrait'),
  ('Les 3 Chênes', 'Vigne Rouge Les 3 Chênes', '60 gélules', 11.5, 'Vigne rouge extrait'),
  ('Pileje', 'Hamamélis Pileje', '30 gélules', 12.9, 'Hamamélis'),
  ('Arkopharma', 'Arkogélules Hamamélis', '45 gélules', 10.9, 'Hamamélis'),
  ('Weleda', 'Hamamélis Extrait Weleda', '30 gélules', 11.5, 'Hamamélis'),
  ('Solgar', 'Rutine 500mg Solgar', '100 comprimés', 12.9, 'Rutine 500mg'),
  ('Arkopharma', 'Rutine 500mg Arkopharma', '60 gélules', 10.9, 'Rutine 500mg'),
  ('NHCO', 'Rutine NHCO', '30 gélules', 13.9, 'Rutine 500mg'),
  ('Arkopharma', 'Arkogélules Mélilot', '45 gélules', 10.9, 'Mélilot extrait'),
  ('Santé Verte', 'Mélilot Santé Verte', '60 gélules', 10.5, 'Mélilot extrait'),
  ('Les 3 Chênes', 'Mélilot Les 3 Chênes', '60 gélules', 11.5, 'Mélilot extrait'),
  ('Naturactive', 'Marronnier d''Inde Naturactive', '30 gélules', 9.9, 'Marronnier d''Inde'),
  ('Arkopharma', 'Arkogélules Marronnier d''Inde', '45 gélules', 10.9, 'Marronnier d''Inde'),
  ('Les 3 Chênes', 'Marronnier d''Inde Les 3 Chênes', '60 gélules', 11.5, 'Marronnier d''Inde'),
  ('Pileje', 'Magnésium Bisglycinate 300mg Pileje', '60 gélules', 15.5, 'Magnésium bisglycinate 300mg'),
  ('Nutergia', 'Ergymag Bisglycinate', '90 gélules', 22.9, 'Magnésium bisglycinate 300mg'),
  ('Solgar', 'Magnésium Bisglycinate Solgar', '120 gélules', 17.5, 'Magnésium bisglycinate 300mg'),
  ('Solgar', 'Ashwagandha 300mg Solgar', '60 gélules', 18.9, 'Ashwagandha 300mg'),
  ('Arkopharma', 'Arkogélules Ashwagandha', '45 gélules', 14.9, 'Ashwagandha 300mg'),
  ('Nutergia', 'Ergyashwagandha 300mg', '60 gélules', 15.9, 'Ashwagandha 300mg'),
  ('Arkopharma', 'Arkogélules Rhodiole', '45 gélules', 14.9, 'Rhodiola rosea'),
  ('Santé Verte', 'Rhodiola Rosea Santé Verte', '60 gélules', 13.9, 'Rhodiola rosea'),
  ('Les 3 Chênes', 'Rhodiola Les 3 Chênes', '60 gélules', 14.5, 'Rhodiola rosea'),
  ('Nutreov', 'Griffonia 100mg Nutreov', '30 gélules', 16.9, 'Griffonia 100mg'),
  ('Arkopharma', 'Arkogélules Griffonia', '45 gélules', 13.9, 'Griffonia 100mg'),
  ('Santé Verte', 'Griffonia 5-HTP Santé Verte', '30 gélules', 14.5, 'Griffonia 100mg'),
  ('Solgar', 'L-Théanine 150mg Solgar', '60 gélules', 19.9, 'L-Théanine 200mg'),
  ('NHCO', 'L-Théanine 200mg NHCO', '30 gélules', 18.9, 'L-Théanine 200mg'),
  ('Nutergia', 'Ergytheanine 200mg', '60 gélules', 17.9, 'L-Théanine 200mg'),
  ('Pileje', 'Magnésium Marin 300mg Pileje', '60 gélules', 12.9, 'Magnésium marin 300mg'),
  ('Nutergia', 'Ergymag Marin 300mg', '90 gélules', 13.9, 'Magnésium marin 300mg'),
  ('Arkopharma', 'Magnésium Marin Arkopharma 300mg', '60 gélules', 10.9, 'Magnésium marin 300mg'),
  ('Arkopharma', 'Arkogélules Gattilier (Vitex)', '45 gélules', 12.9, 'Vitex agnus-castus'),
  ('Santé Verte', 'Gattilier Vitex Santé Verte', '60 gélules', 12.5, 'Vitex agnus-castus'),
  ('Les 3 Chênes', 'Gattilier Les 3 Chênes', '60 gélules', 13.5, 'Vitex agnus-castus'),
  ('Ixora', 'Safran 15mg Ixora', '30 gélules', 14.9, 'Safran 15mg'),
  ('Nutergia', 'Ergysafran 15mg', '30 gélules', 15.9, 'Safran 15mg'),
  ('Arkopharma', 'Arkogélules Safran', '30 gélules', 13.9, 'Safran 15mg'),
  ('Pileje', 'Oméganut EPA/DHA Pileje', '60 gélules · EPA 450/DHA 300mg', 15.9, 'Oméga-3 EPA/DHA'),
  ('Nutergia', 'Ergyomega EPA/DHA', '60 gélules', 15.9, 'Oméga-3 EPA/DHA'),
  ('Solgar', 'Oméga-3 Triple Force Solgar', '100 gélules', 21.9, 'Oméga-3 EPA/DHA'),
  ('Solgar', 'Curcumine Full Spectrum 500mg Solgar', '60 gélules', 22.9, 'Curcumine 500mg'),
  ('Pileje', 'Curcumaxx C3 500mg Pileje', '60 gélules', 14.9, 'Curcumine 500mg'),
  ('Bayer', 'Supradyn Intensia', '30 comprimés — multivitamines + ginseng', 13.9, 'Multivitamines complexe'),
  ('Bayer', 'Supradyn Vital 50+', '30 comprimés — multivitamines senior', 16.9, 'Multivitamines complexe'),
  ('UPSA', 'Multivitamines 5en1 UPSA', '20 gummies', 8.99, 'Multivitamines complexe'),
  ('Haleon', 'Centrum Adultes', '100 comprimés — formule complète', 11, 'Multivitamines complexe'),
  ('Haleon', 'Centrum Women', '60 comprimés — formule femme', 11.89, 'Multivitamines complexe'),
  ('Haleon', 'Centrum Men', '60 comprimés — formule homme', 17.91, 'Multivitamines complexe')
ON CONFLICT (lab, name) DO UPDATE SET
  dosage = EXCLUDED.dosage,
  prix = EXCLUDED.prix,
  category = EXCLUDED.category,
  updated_at = now();
